### ISSUE TITLE
Пользователь уже начал редактировать эти данные

### ISSUE THREAD

**Issue by Evg-lylyk** [Evg-lylyk/DC3BoosterISToolkit#1]
Если отредактировать какой-то элемент например правило, то при повторном входе возникает проблема
"Пользователь уже начал редактировать эти данные"

**Comment by GenVP** [comment]
Скорее всего проблема в тулките.  ​Эта ошибка воспроизводится даже, если просто открыть форму, записать, затем снова открыть и записать.

Причина:
При открытии формы вызывается инициализация редактора кода. В этой процедуре инициализации формируется структура доп. параметров, в которую добавляется оповещение завершения инициализации со ссылкой на эту же структуру.
Если этого не делать, а передавать в конечное оповещение завершения инициализации данные явно через результат, а не автоматом через доп. параметры, то ошибки не будет.

**Comment by Evg-lylyk** [comment]
> Скорее всего проблема в тулките. ​Эта ошибка воспроизводится даже, если просто открыть форму, записать, затем снова открыть и записать.
> 
> Причина:
> При открытии формы вызывается инициализация редактора кода. В этой процедуре инициализации формируется структура доп. параметров, в которую добавляется оповещение завершения инициализации со ссылкой на эту же структуру.
> Если этого не делать, а передавать в конечное оповещение завершения инициализации данные явно через результат, а не автоматом через доп. параметры, то ошибки не будет.

Спасибо, исправил. Будет в версии 1.0.2
