### ISSUE TITLE
Ошибка при открытии правил регистрации

### ISSUE THREAD

**Issue by AnanyevAl** [Evg-lylyk/DC3BoosterISToolkit#12]
При открытии правил регистрации выходит ошибка:
Поле объекта не обнаружено (ТипКонвертации)
{DC3BoosterISToolkit ОбщийМодуль.КД3ИТК_ПодключениеРедактораКодаКлиент.Модуль(416)}:		Результат = ОбъектФормы.ТипКонвертации;
{DC3BoosterISToolkit ОбщийМодуль.КД3ИТК_ПодключениеРедактораКодаКлиент.Модуль(287)}:	ТипКонвертации = ТипКонвертации(Форма);
{DC3BoosterISToolkit ОбщийМодуль.КД3ИТК_ПодключениеРедактораКодаКлиент.Модуль(24)}:	Источник = ИсточникМетаданных(Форма, Элемент);
{DC3BoosterISToolkit Справочник.ПравилаРегистрацииОбъектов.Форма.ФормаЭлемента.Форма(6)}:	КД3ИТК_ПодключениеРедактораКодаКлиент.ДокументСформирован(ЭтотОбъект, Элемент);

**Comment by Evg-lylyk** [comment]
Какая у тебя версия?
В 1.0.3 исправлял такую ошибку
https://github.com/Evg-lylyk/DC3BoosterISToolkit/releases/tag/1.0.3
