### ISSUE TITLE
Поиск по коду - выполняется сразу при выборе конвертации

### ISSUE THREAD

**Issue by AnanyevAl** [Evg-lylyk/DC3BoosterISToolkit#13]
Поиск по коду сразу начинает выполнение при выборе конвертации, даже если строка поиска еще не введена.
Сценарий использования:
1. Находимся в форме настройки правил конвертации
2. Вызываем поиск по коду (Ctrl+Shift+F)
3. При открытии формы поиска поле конвертации не заполнено, выбираем конвертацию (строка поиска пустая)
4. Форма поиска подвисает и на долго, предполагаю что идет поиск пустой строки.

Думаю нужна проверка на заполненность строки поиска.

**Comment by Evg-lylyk** [comment]
Спасибо, исправлено в 1.0.4
