### ISSUE TITLE
При инициализации фокус висит на редакторе а начать редактирование невозможно

### ISSUE THREAD

**Issue by Evg-lylyk** [Evg-lylyk/DC3BoosterISToolkit#2]
Необходимо повторно присвоить фокус

**Comment by GenVP** [comment]
Такая проблема возникает на обработчиках "Конвертации" для XML. Одна из причин - попытка переключения фокуса на элемент невидимый таблицы версий формата.

Можно исправить так:
1. В "Конвертации" добавить после формирования документа подключения обработчика смены фокуса.
2. В Толките в обработчике смены фокуса добавить рекурсивную проверку видимости родителя нужного элемента чтобы исключить невидимые элементы (на них фокус не переключится).

**Comment by Evg-lylyk** [comment]
> Такая проблема возникает на обработчиках "Конвертации" для XML. Одна из причин - попытка переключения фокуса на элемент невидимый таблицы версий формата.
> 
> Можно исправить так:
> ... 

Спасибо большое, попробую
