### ISSUE TITLE
Ошибка при добавлении нового ПКО

### ISSUE THREAD

**Issue by AnanyevAl** [Evg-lylyk/DC3BoosterISToolkit#21]
При добавлении нового ПКО в настройке правил конвертации XML выходит ошибка:
{(8, 30)}: Неверные параметры в операции сравнения. Нельзя сравнивать поля неограниченной длины и поля несовместимых типов.
Отчет по ошибке : [https://drive.google.com/file/d/1vlFxliKG_72BGXjvJMO4p_pXqexoeblQ/view?usp=sharing](url)

**Comment by Evg-lylyk** [comment]
Ошибка исправлена в 1.0.6
Сейчас можно в модуле КД3ИТК_ПодключениеРедактораКодаКлиент
заменить код функции 
https://paste1c.ru/6ty144xgk3jh
