### ISSUE TITLE
Контекстная подсказка в обработчиках событий "При загрузке" и "После загрузки"

### ISSUE THREAD

**Issue by AnanyevAl** [Evg-lylyk/DC3BoosterISToolkit#22]
Настраиваем правила конвертации XML.
Для ПКО у которых тип приемника "Документ" в обработчиках "При загрузке" и "После загрузки" для переменной "Объект" не выходит контекстная подсказка с доступными для него свойствами.
Для ПКО у которых тип приемника "Справочник" все работает замечательно.

**Comment by Evg-lylyk** [comment]
Посмотри сам глубже пожалуйста, у меня работает.
https://gifyu.com/image/S2B38

**Comment by AnanyevAl** [comment]
Еще перепроверил, загрузил первую попавшуюся типовую конвертацию.
Действительно, работает.
Но вот в тех правилах с которыми работаю сейчас происходит это: [https://www.youtube.com/watch?v=JWkTTdxeUk8](https://www.youtube.com/watch?v=JWkTTdxeUk8)

**Comment by Evg-lylyk** [comment]
Не могу посмотреть видео "Видео недоступно. Автор ограничил доступ к видео."

**Comment by AnanyevAl** [comment]
Открыл доступ по ссылке

**Comment by Evg-lylyk** [comment]
Вижу не работает, да я и до этого верил что такое может быть.
Не знаю как почему такое может происходить
Посмотри глубже (точку останова как на картинке).
![image](https://user-images.githubusercontent.com/48444742/145394329-fe2c77f6-3daa-4fda-8e84-afd1297a38d1.png)
Опишу как это работает для поля Объект назначается тип "Документ.Реализация" в момент использования Объект. 
происходит считывание поле подсказки. Могу подключиться и на месте посмотреть, можешь со мной списаться в телеге https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Спасибо за информацию, ошибка будет исправлена в следующей версии 1.0.6
