### ISSUE TITLE
XML. Добавить подсказку для ПГКС

### ISSUE THREAD

**Issue by GenVP** [Evg-lylyk/DC3BoosterISToolkit#6]
Добавить подсказку в форму "Правило конвертации группы" для ПКС.

Пример:
Демо КД3. Конвертация "БП --> УП 3_0_82 - 2_4_13 v.2".
ПКО "Контрагенты"-"Контрагенты_Контрагенты".
Группа "Контактная информация".

![image](https://user-images.githubusercontent.com/34754769/133642245-86d3ca83-6804-4b86-994e-604f1dba87d5.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 1.0.1, пока без контекстов
